apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: api
  template: 
    metadata:       
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: daniel10souza/api-produto:58: #cria uma tag para utilizar no deploy do Jenkinsfile
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
            cpu: 40m
          limits:
            memory: 256Mi
            cpu: 100m
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
          - name: Mongo__User
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: mongodb-secret
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: mongodb-secret
